name: Lint

on:
  workflow_run:
    workflows: ["Black Formatter"]
    branches: ["main"]
    types: 
      - completed
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install lint requirements
        run: pip install -r requirements.txt
      - name: Run lint
        run: flake8 Codes
